output: mythx.txt
format: table

analyze:
    scenario: solidity
    mode: standard
    create-group: true
    group-name: facecoin-edition
    remappings:
        - "@openzeppelin/=./node_modules/@openzeppelin/"